listener 8789 @AP_ADDRESS@
allow_anonymous true
require_certificate false
certfile /etc/m5c-local/certs/server.crt
keyfile /etc/m5c-local/certs/server.key
log_type notice
log_timestamp true
connection_messages true
log_dest stdout
